dist: xenial
language: python
python:
    - 3.7
sudo: required
services:
    - docker
install:
    - pip install --upgrade pip
    - make test-env
script:
    - set -e
    - make build
    - make test
